import { useEffect,useState,type FormEvent } from 'react';
import { Link,NavLink,Redirect,Route,Switch,useHistory } from 'react-router-dom';
import { Button,Notice } from '../../components/OperationsUI';
import { api,mutate,DEMO_MODE } from '../../utils/api';
import Dashboard from './Dashboard';
import Orders from './Orders';
import Products from './Products';
import Reservations from './Reservations';
import SettingsPage from './Settings';
interface Session{email:string;expiresAt:number;}
export default function Admin(){if(DEMO_MODE)return <section className="admin-login"><p className="section-kicker">Geschützter Team-Zugang</p><h1>Admin-Anmeldung</h1><p>Die Anmeldung ist noch nicht freigeschaltet. Dafür muss der sichere Shop-Server verbunden sein. Verwaltungs- und Kundendaten sind öffentlich nicht zugänglich.</p><Link to="/">Zur Startseite</Link></section>;return <ConnectedAdmin/>;}
function ConnectedAdmin(){const [session,setSession]=useState<Session>();const [loading,setLoading]=useState(true);const history=useHistory();
 useEffect(()=>{let active=true;const verify=async()=>{try{const result=await api<Session>('/auth/verify');if(active)setSession(result);}catch{if(active)setSession(undefined);}finally{if(active)setLoading(false);}};void verify();const timer=window.setInterval(()=>void verify(),45000);const logout=()=>{setSession(undefined);history.replace('/admin/login');};window.addEventListener('urfa:logout',logout);return()=>{active=false;window.clearInterval(timer);window.removeEventListener('urfa:logout',logout);};},[history]);
 if(loading)return <div className="admin-page"><Notice>Sitzung wird geprüft …</Notice></div>;
 if(!session)return <><Route path="/admin/login"><Login onLogin={setSession}/></Route><Route path="/admin" exact><Redirect to="/admin/login"/></Route><Route path="/admin/:section" render={({match})=>match.params.section!=='login'?<Redirect to="/admin/login"/>:null}/></>;
 return <div className="admin-layout"><aside className="admin-sidebar"><p className="section-kicker">Urfa Verwaltung</p><p>{session.email}</p><nav aria-label="Verwaltung"><NavLink exact to="/admin">Übersicht</NavLink><NavLink to="/admin/pedidos">Bestellungen</NavLink><NavLink to="/admin/produtos">Produkte</NavLink><NavLink to="/admin/reservas">Reservierungen</NavLink><NavLink to="/admin/settings">Einstellungen</NavLink></nav><Button variant="secondary" onClick={async()=>{try{await mutate('/auth/logout','POST');}catch{window.alert('Abmelden fehlgeschlagen. Bitte erneut versuchen.');return;}setSession(undefined);history.replace('/admin/login');}}>Abmelden</Button></aside><div className="admin-main"><Switch><Route path="/admin/login"><Redirect to="/admin"/></Route><Route path="/admin/pedidos" component={Orders}/><Route path="/admin/produtos" component={Products}/><Route path="/admin/reservas" component={Reservations}/><Route path="/admin/settings" component={SettingsPage}/><Route exact path="/admin" component={Dashboard}/><Route><Notice error>Verwaltungsseite nicht gefunden.</Notice><Link to="/admin">Zur Übersicht</Link></Route></Switch></div></div>;
}
function Login({onLogin}:{onLogin:(s:Session)=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);const history=useHistory();const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{const session=await mutate<Session>('/auth/login','POST',{email:data.get('email'),password:data.get('password')});onLogin(session);history.replace('/admin');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};return <section className="admin-login"><p className="section-kicker">Nur für Mitarbeitende</p><h1>Willkommen zurück.</h1><form className="op-card op-form" onSubmit={submit}><label>Email<input type="email" name="email" required autoComplete="username"/></label><label>Passwort<input type="password" name="password" required autoComplete="current-password"/></label>{error&&<Notice error>{error}</Notice>}<Button type="submit" disabled={busy}>{busy?'Anmeldung …':'Anmelden'}</Button></form></section>;}
