import { useState } from 'react';
import PrivateCarts from './PrivateCarts';
import { Link } from 'react-router-dom';
import { useResource } from '../../hooks/useResource';
import { Button,Notice } from '../../components/OperationsUI';
import { mutate } from '../../utils/api';
import { cents,type Settings } from '../operations';
interface DashboardData{pending:number;reservations:number;revenueCents:number;periodRevenueCents:number;averagePreparation:number|null;week:{day:string;count:string}[];top:[string,number][];settings:Settings;emailEnabled:boolean;failedEmails:number;}
export default function Dashboard(){const [period,setPeriod]=useState('today');const {data,error,reload}=useResource<DashboardData>(`/admin/dashboard?period=${period}`,15000);const [actionError,setActionError]=useState('');const [busy,setBusy]=useState(false);
 return <><div className="admin-heading"><div><p className="section-kicker">Heute in Hildesheim</p><h1>Alles im Blick.</h1></div>{data&&<Button disabled={busy} variant={data.settings.isOpen?'secondary':'primary'} onClick={async()=>{setBusy(true);try{await mutate('/settings','PUT',{...data.settings,isOpen:!data.settings.isOpen});await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}}>{data.settings.isOpen?'Annahme pausieren':'Annahme öffnen'}</Button>}</div>{(error||actionError)&&<Notice error>{error||actionError}</Notice>}{!data&&!error&&<Notice>Übersicht wird geladen …</Notice>}{data&&<><div className="stat-grid"><Link className="op-card" to="/admin/pedidos"><span>Offene Bestellungen heute</span><strong>{data.pending}</strong></Link><Link className="op-card" to="/admin/reservas"><span>Bestätigte Reservierungen heute</span><strong>{data.reservations}</strong></Link><div className="op-card"><span>Abgeholte Bestellungen heute</span><strong>{cents(data.revenueCents)}</strong></div><div className="op-card"><span>Ø Zubereitung heute</span><strong>{data.averagePreparation===null?'Noch keine Daten':`${data.averagePreparation} Min.`}</strong></div></div><div className="op-actions"><Link className="op-button primary" to="/admin/pedidos">Bestellungen bearbeiten</Link><Link className="op-button secondary" to="/admin/reservas">Reservierungskalender</Link><Link className="op-button secondary" to="/admin/produtos">Lagerbestand</Link></div>{!data.emailEnabled&&<Notice>Emailversand ist nicht eingerichtet. Statusänderungen bleiben online sichtbar.</Notice>}{data.failedEmails>0&&<Notice error>{data.failedEmails} Emails konnten nicht zugestellt werden. Versanddienst prüfen.</Notice>}<section className="op-card"><h2>Berichte</h2><label>Zeitraum <select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Heute</option><option value="week">Diese Woche</option><option value="month">Dieser Monat</option></select></label><p>Wert abgeholter Bestellungen: <strong>{cents(data.periodRevenueCents)}</strong></p><p className="muted">Bestellwert, kein Zahlungs- oder Buchhaltungsnachweis.</p><h3>Bestellungen der letzten sieben Tage</h3><div className="mini-chart">{data.week.length?data.week.map(day=><div key={day.day}><span>{day.day}</span><meter min={0} max={Math.max(...data.week.map(d=>Number(d.count)),1)} value={Number(day.count)}/><strong>{day.count}</strong></div>):<p>Noch keine Bestellungen.</p>}</div><PrivateCarts/><h3>Meistverkaufte Produkte im Zeitraum</h3>{data.top.length?<ol>{data.top.map(([name,count])=><li key={name}>{name} — {count}</li>)}</ol>:<p>Noch keine abgeschlossenen Bestellungen.</p>}</section></>}</>;
}
