import { useEffect,useRef,useState } from 'react';
import { useResource } from '../../hooks/useResource';
import { Badge,Button,Notice,Timeline } from '../../components/OperationsUI';
import { mutate } from '../../utils/api';
import { cents,dateLabel,statusLabels,type Order } from '../operations';
const nextStatus:Record<string,string>={pending:'confirmed',confirmed:'preparing',preparing:'ready',ready:'delivered'};
export default function Orders(){const [period,setPeriod]=useState('today');const [status,setStatus]=useState('');const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [expanded,setExpanded]=useState('');const [error,setError]=useState('');const [toast,setToast]=useState('');const [busy,setBusy]=useState(false);const seen=useRef<Set<string>>();
 const {data,loading,error:loadError,reload}=useResource<Order[]>(`/orders?period=${period}&status=${status}&q=${encodeURIComponent(search)}`,10000);
 useEffect(()=>{const t=window.setTimeout(()=>setSearch(query),250);return()=>clearTimeout(t);},[query]);
 useEffect(()=>{seen.current=undefined;},[period,status,search]);
 useEffect(()=>{if(!data)return;if(seen.current&&data.some(o=>!seen.current!.has(o.id)))setToast('Neue Bestellung eingegangen.');seen.current=new Set(data.map(o=>o.id));},[data]);
 const change=async(order:Order,status:string)=>{setBusy(true);setError('');try{await mutate(`/orders/${order.id}/status`,'PUT',{status});await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><h1>Bestellungen</h1><div className="admin-filters"><label>Zeitraum<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Heute</option><option value="week">Diese Woche</option><option value="month">Dieser Monat</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle</option>{Object.entries(statusLabels).filter(([s])=>s!=='cancelled').map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></label><label>Suche<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bestellnummer oder Name"/></label></div>{toast&&<div className="op-toast" role="status">{toast}<button onClick={()=>setToast('')}>Schließen</button></div>}{(error||loadError)&&<Notice error>{error||loadError}</Notice>}{loading&&<Notice>Bestellungen werden geladen …</Notice>}{data?.length===0&&<Notice>Keine Bestellungen für diesen Filter.</Notice>}<div className="order-admin-list">{data?.map(order=><article className="op-card" key={order.id}><button className="order-summary-button" aria-expanded={expanded===order.id} onClick={()=>setExpanded(expanded===order.id?'':order.id)}><span><strong className="record-id">{order.order_number}</strong><small>{order.customer.name} · {dateLabel(order.created_at)}</small></span><span>{order.items.reduce((s,i)=>s+i.quantity,0)} Artikel</span><strong>{cents(order.total_cents)}</strong><Badge status={order.status}/></button>{expanded===order.id&&<div className="order-expanded"><div><h3>Kunde</h3><p>{order.customer.name}<br/>{order.customer.email}<br/>{order.customer.phone}<br/>{order.customer.address}</p><p>Abholung: {dateLabel(order.pickup_at)}</p><p>Hinweise: {order.notes||'Keine'}</p>{order.items.map((item,i)=><div className="summary-item" key={i}><strong>{item.quantity} × {item.name}</strong><span>{cents(item.unitCents)} / Stück</span><small>{item.options.map(o=>`${o.groupName}: ${o.optionName}`).concat(item.extras).join(' · ')}</small></div>)}<p>Gesamt inkl. ausgewiesener Produktpreise: {cents(order.total_cents)} · Abholung ohne Liefergebühr.</p></div><Timeline history={order.history} status={order.status}/></div>}<div className="op-actions">{nextStatus[order.status]&&<Button disabled={busy} onClick={()=>void change(order,nextStatus[order.status])}>{statusLabels[nextStatus[order.status]]}</Button>}{order.status==='pending'&&<Button disabled={busy} variant="danger" onClick={()=>{if(window.confirm('Bestellung ablehnen?'))void change(order,'rejected');}}>Ablehnen</Button>}<Button variant="ghost" disabled={busy} onClick={async()=>{try{await mutate(`/orders/${order.id}/notify`,'POST');setToast('Status-Email zum Versand vorgemerkt.');}catch(e){setError((e as Error).message);}}}>Status per Email senden</Button></div></article>)}</div></>;
}
