import { useState,type FormEvent } from 'react';
import { useResource } from '../../hooks/useResource';
import { Button,Modal,Notice } from '../../components/OperationsUI';
import { mutate } from '../../utils/api';
import type { Product } from '../../types';
import { formatPrice } from '../../utils/formatPrice';
import categories from '../../data/categories.json';
export default function Products(){const {data,error:loadError,reload}=useResource<Product[]>('/admin/products');const [editing,setEditing]=useState<Product|null>();const [category,setCategory]=useState('');const [search,setSearch]=useState('');const [sort,setSort]=useState('name');const [error,setError]=useState('');
 const {data:analytics}=useResource<{popularity:Record<string,number>}>('/admin/dashboard?period=month');const popularity=analytics?.popularity||{};
 const visible=(data||[]).filter(p=>(!category||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='popularity'?(popularity[b.name]||0)-(popularity[a.name]||0):a.name.localeCompare(b.name,'de'));
 return <><div className="admin-heading"><h1>Produkte</h1><Button onClick={()=>setEditing(null)}>Neues Produkt</Button></div><div className="admin-filters"><label>Name<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Kategorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Alle</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Sortierung<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">A–Z</option><option value="price">Preis</option><option value="popularity">Beliebtheit (Monat)</option></select></label></div>{(error||loadError)&&<Notice error>{error||loadError}</Notice>}<div className="op-table-wrap"><table><thead><tr><th>Name</th><th>Kategorie</th><th>Preis</th><th>Verfügbarkeit</th><th>Aktionen</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.category}</td><td>{formatPrice(p.price)}</td><td>{p.available&&p.stockAvailable?'Verfügbar':!p.available?'Inaktiv':'Ausverkauft'}</td><td><div className="op-actions"><Button variant="ghost" onClick={()=>setEditing(p)}>Bearbeiten</Button><Button variant="danger" onClick={async()=>{if(!window.confirm(`${p.name} aus der Speisekarte entfernen? Das Produkt bleibt im Änderungsprotokoll erhalten.`))return;try{await mutate(`/products/${p.id}`,'DELETE');await reload();}catch(e){setError((e as Error).message);}}}>Entfernen</Button></div></td></tr>)}</tbody></table></div>{editing!==undefined&&<ProductEditor product={editing} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await reload();}}/>}</>;
}
function ProductEditor({product,onClose,onSaved}:{product:Product|null;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget);try{const options=JSON.parse(String(d.get('options')||'[]'));const extras=JSON.parse(String(d.get('extras')||'[]'));await mutate(product?`/products/${product.id}`:'/products',product?'PUT':'POST',{...product, name:d.get('name'),description:d.get('description'),category:d.get('category'),price:Number(d.get('price')),imageUrl:d.get('imageUrl'),available:d.has('available'),stockAvailable:d.has('stock'),featured:d.has('featured'),ingredients:String(d.get('ingredients')||'').split(',').map(s=>s.trim()).filter(Boolean),modelUrl:d.get('modelUrl')||'',internalNotes:d.get('notes'),optionGroups:options,variants:JSON.parse(String(d.get('variants')||'[]')),extras});onSaved();}catch(e){setError(e instanceof SyntaxError?'Optionen und Extras müssen gültiges JSON enthalten.':(e as Error).message);}finally{setBusy(false);}};
 return <Modal title={product?'Produkt bearbeiten':'Neues Produkt'} onClose={onClose}><form className="op-form" onSubmit={submit}><label>Name<input name="name" required maxLength={120} defaultValue={product?.name}/></label><label>Beschreibung<textarea name="description" maxLength={2000} defaultValue={product?.description}/></label><div className="form-columns"><label>Kategorie<select name="category" defaultValue={product?.category||categories[0]}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Preis (EUR)<input name="price" required type="number" min={0} max={10000} step="0.01" defaultValue={product?.price}/></label></div><label>Bild-URL (HTTPS)<input name="imageUrl" defaultValue={product?.imageUrl||''} placeholder="https://…"/></label><p className="muted">Verwende ein optimiertes Produktbild. Bestehende lokale Bilder bleiben erhalten.</p><label className="check-label"><input name="available" type="checkbox" defaultChecked={product?.available??true}/>Aktiv</label><label className="check-label"><input name="stock" type="checkbox" defaultChecked={product?.stockAvailable??true}/>Auf Lager</label><label className="check-label"><input name="featured" type="checkbox" defaultChecked={product?.featured??false}/>Auf Startseite hervorheben</label><label>Interne Notizen<textarea name="notes" maxLength={2000} defaultValue={product?.internalNotes}/></label><label>Bestätigte Zutaten (mit Komma trennen)<textarea name="ingredients" defaultValue={product?.ingredients?.join(', ')}/></label><label>3D-Modell-URL (optional, GLB/GLTF)<input name="modelUrl" defaultValue={product?.modelUrl}/></label><details><summary>Varianten und Extras (JSON)</summary><p>Varianten: id, name, required, options (id, name, price). Extras: id, name, price.</p><label>Größen mit eigenen Optionen (JSON)<textarea name="variants" rows={5} defaultValue={JSON.stringify(product?.variants||[],null,2)}/></label><label>Auswahlgruppen<textarea name="options" rows={7} defaultValue={JSON.stringify(product?.optionGroups||[],null,2)}/></label><label>Extras<textarea name="extras" rows={5} defaultValue={JSON.stringify(product?.extras||[],null,2)}/></label></details>{error&&<Notice error>{error}</Notice>}<Button type="submit" disabled={busy}>{busy?'Speichern …':'Speichern'}</Button></form></Modal>;
}
