import { useEffect,useRef,useState } from 'react';
import { useLocation,useParams } from 'react-router-dom';
import { api } from '../utils/api';
import { Badge,Notice,Timeline } from '../components/OperationsUI';
import { cents,dateLabel,statusLabels,type OrderItem,type HistoryEntry } from '../features/operations';
interface TrackingData{number:string;items:OrderItem[];totalCents:number;status:string;history:HistoryEntry[];pickupAt:string;estimatedMinutes:number;}
export default function Tracking(){
 const {id}=useParams<{id:string}>();const token=new URLSearchParams(useLocation().search).get('token')||'';const [data,setData]=useState<TrackingData>();const [error,setError]=useState('');const [toast,setToast]=useState('');const previous=useRef('');
 useEffect(()=>{let stopped=false;const load=async()=>{try{const next=await api<TrackingData>(`/orders/${id}`,{headers:{'X-Order-Token':token}},false);if(stopped)return;if(previous.current&&previous.current!==next.status)setToast(`Deine Bestellung: ${statusLabels[next.status]}`);previous.current=next.status;setData(next);setError('');}catch(e){if(!stopped)setError((e as Error).message);}};void load();const timer=window.setInterval(()=>{if(!document.hidden)void load();},10000);return()=>{stopped=true;window.clearInterval(timer);};},[id,token]);
 return <section className="tracking-page"><p className="section-kicker">Deine Bestellung</p><h1>Frisch in Zubereitung.</h1>{toast&&<div className="op-toast" role="status">{toast}<button onClick={()=>setToast('')}>Schließen</button></div>}{error&&<Notice error>{error}</Notice>}{!data&&!error&&<Notice>Status wird geladen …</Notice>}{data&&<div className="tracking-grid"><div className="op-card"><p className="record-id">{data.number}</p><Badge status={data.status}/><Timeline history={data.history} status={data.status}/></div><div className="op-card"><h2>Bestellübersicht</h2>{data.items.map((item,i)=><div className="summary-item" key={i}><strong>{item.quantity} × {item.name}</strong><span>{cents(item.unitCents*item.quantity)}</span><small>{item.options.map(o=>o.optionName).concat(item.extras).join(', ')}</small></div>)}<p><strong>Gesamt: {cents(data.totalCents)}</strong></p><p>Gewünschte Abholung: {dateLabel(data.pickupAt)}</p><p>Übliche Zubereitung: ca. {data.estimatedMinutes} Minuten. Der Status wird vom Restaurant aktualisiert.</p><Notice>Bewahre diesen privaten Link auf. Teile ihn nur mit Personen, die deinen Bestellstatus sehen dürfen.</Notice></div></div>}</section>;
}
