import { useEffect, useId, useRef, type ReactNode, type ButtonHTMLAttributes } from 'react';
import { statusLabels } from '../features/operations';
export function Button({variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'danger'|'ghost'}){return <button type="button" {...props} className={`op-button ${variant} ${props.className || ''}`}/>;}
export function Badge({status}:{status:string}){return <span className={`status-badge status-${status}`}>{statusLabels[status] || status}</span>;}
export function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <p className={`op-notice ${error?'error':''}`} role={error?'alert':'status'}>{children}</p>;}
export function Timeline({history,status}:{history:{status:string;at:string}[];status:string}){const steps=['pending','confirmed','preparing','ready','delivered'];return <ol className="order-timeline">{(status==='rejected'?['pending','rejected']:steps).map(step=>{const event=history.find(h=>h.status===step);return <li key={step} className={event?'complete':''}><span className="timeline-dot"/><div><strong>{statusLabels[step]}</strong><small>{event?new Date(event.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Berlin'}):'Ausstehend'}</small></div></li>;})}</ol>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null);const id=useId();const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close.current();if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select,textarea,a[href]')||[]);const a=nodes[0],b=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b?.focus();}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className="op-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className="op-modal" role="dialog" aria-modal="true" aria-labelledby={id}><header><h2 id={id}>{title}</h2><Button variant="ghost" aria-label="Fenster schließen" onClick={onClose}>Schließen</Button></header>{children}</div></div>;
}
