import { requestId } from '../../utils/requestId';
import { useState, type FormEvent } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { Button,Notice,Badge } from '../../components/OperationsUI';
import { useResource } from '../../hooks/useResource';
import { api,mutate } from '../../utils/api';
import { berlinDate,type Settings } from '../operations';
interface Slot{time:string;available:boolean;availableTables:number;}
interface BookingResult{id:string;number:string;status:string;cancellationToken:string;email:string;}
export default function Booking(){
 const {data:settings,error:settingsError}=useResource<Settings>('/settings');
 const [step,setStep]=useState(1);const [date,setDate]=useState('');const [time,setTime]=useState('');const [people,setPeople]=useState(1);const [name,setName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [notes,setNotes]=useState('');const [smsOptIn,setSmsOptIn]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<BookingResult>();const [requestKey,setRequestKey]=useState(()=>requestId());
 const {data:slots,error:slotError,loading}=useResource<Slot[]>(date?`/reservations/availability?date=${date}&people=${people}`:null,15000);
 const selected=slots?.find(s=>s.time===time);const reset=()=>{setRequestKey(requestId());setError('');};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(step<4){setStep(step+1);return;}setBusy(true);setError('');try{const response=await mutate<BookingResult>('/reservations','POST',{date,time,people,customer:{name,email,phone,smsOptIn},notes,requestKey});setResult(response);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(result)return <section className="booking-page"><div className="success-check" aria-hidden="true">✓</div><h1>{result.status==='confirmed'?'Reservierung bestätigt!':'Reservierungsanfrage eingegangen'}</h1><p className="record-id">{result.number}</p><Badge status={result.status}/><p>{date} um {time} Uhr · {people} Personen</p><p>{result.status==='pending'?'Der Tisch wird vorläufig gehalten. Das Restaurant bestätigt deine Anfrage.':'Wir freuen uns auf deinen Besuch.'}</p><Notice>{result.email==='queued'?`Eine Email an ${email} wurde zum Versand vorgemerkt.`:'Emailversand ist nicht eingerichtet. Speichere bitte Nummer und Stornierungslink.'}</Notice><Link to={`/reservar/cancelar/${result.id}?token=${result.cancellationToken}`}>Reservierung stornieren</Link><p><Link to="/">Zur Startseite</Link></p></section>;
 return <section className="booking-page"><p className="section-kicker">Urfa Grill · Hildesheim</p><h1>Ein Tisch für euch.</h1><p>Reserviere deinen Besuch in der Schuhstraße 39. Alle Zeiten gelten für Hildesheim.</p><ol className="booking-steps">{['Datum & Zeit','Personen','Kontakt','Prüfen'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined}>{i+1}. {label}</li>)}</ol>{settingsError&&<Notice error>{settingsError}</Notice>}{settings&&!settings.isOpen&&<Notice>Reservierungen sind derzeit pausiert.</Notice>}
 <form className="op-card op-form" onSubmit={submit}>
 {step===1&&<><h2>Wann möchtest du kommen?</h2><label>Datum<input type="date" required min={berlinDate()} value={date} onChange={e=>{setDate(e.target.value);setTime('');reset();}}/></label>{loading&&date&&<Notice>Freie Tische werden geprüft …</Notice>}{slotError&&<Notice error>{slotError}</Notice>}<div className="slot-grid">{slots?.map(slot=><button type="button" aria-pressed={time===slot.time} disabled={!slot.available} key={slot.time} onClick={()=>{setTime(slot.time);reset();}}>{slot.time}</button>)}</div>{date&&slots?.length===0&&<Notice>An diesem Tag sind keine Reservierungen möglich.</Notice>}</>}
 {step===2&&<><h2>Wie viele Personen?</h2><label>Personen<input type="number" min={1} max={20} required value={people} onChange={e=>{setPeople(Number(e.target.value));reset();}}/></label><Notice>{selected?.available?`${selected.availableTables} passende Tische für ${people} Personen verfügbar.`:'Für diese Personenzahl ist der gewählte Termin nicht verfügbar. Bitte zurückgehen und eine andere Zeit wählen.'}</Notice></>}
 {step===3&&<><h2>Wie erreichen wir dich?</h2><label>Name<input autoComplete="name" required minLength={2} maxLength={120} value={name} onChange={e=>{setName(e.target.value);reset();}}/></label><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>{setEmail(e.target.value);reset();}}/></label><label>Telefon<input type="tel" autoComplete="tel" pattern="\+?[0-9]{10,15}" title="10–15 Ziffern, optional mit +" required value={phone} onChange={e=>{setPhone(e.target.value);reset();}}/></label>{settings?.smsEnabled&&<label className="check-label"><input type="checkbox" checked={smsOptIn} onChange={e=>{setSmsOptIn(e.target.checked);reset();}}/>Optional: Reservierungserinnerung per SMS (Telefon mit +Ländervorwahl)</label>}<label>Hinweise (optional)<textarea maxLength={2000} value={notes} onChange={e=>{setNotes(e.target.value);reset();}}/></label></>}
 {step===4&&<><h2>Deine Reservierung</h2><dl className="summary-list"><div><dt>Besuch</dt><dd>{date}, {time} Uhr</dd></div><div><dt>Personen</dt><dd>{people}</dd></div><div><dt>Name</dt><dd>{name}</dd></div><div><dt>Email</dt><dd>{email}</dd></div><div><dt>Telefon</dt><dd>{phone}</dd></div></dl><p>{settings?.autoConfirm?'Freie Tische werden direkt bestätigt.':'Das Restaurant prüft und bestätigt deine Anfrage.'}</p><p>Deine Kontaktdaten werden zur Bearbeitung der Reservierung verwendet.</p></>}
 {error&&<Notice error>{error}</Notice>}<div className="op-actions">{step>1&&<Button variant="secondary" disabled={busy} onClick={()=>setStep(step-1)}>Zurück</Button>}<Button type="submit" disabled={busy||!settings?.isOpen||((step===1||step===2)&&!selected?.available)}>{busy?'Wird gesendet …':step===4?'Reservierung anfragen':'Weiter'}</Button></div></form></section>;
}
export function CancelBooking(){const {id}=useParams<{id:string}>();const token=new URLSearchParams(useLocation().search).get('token')||'';const [done,setDone]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <section className="booking-page"><h1>Reservierung stornieren</h1>{done?<Notice>Deine Reservierung wurde storniert.</Notice>:<><p>Möchtest du deine Reservierung wirklich stornieren?</p><Button variant="danger" disabled={busy||!token} onClick={async()=>{setBusy(true);try{await api(`/reservations/${id}/cancel`,{method:'POST',body:'{}',headers:{'X-Reservation-Token':token}});setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Stornierung bestätigen</Button></>}{error&&<Notice error>{error}</Notice>}<p><Link to="/">Zur Startseite</Link></p></section>;}
