import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {openDatabase,migrate} from '../db.mjs';
import {createApp} from '../app.mjs';
import {config} from '../config.mjs';
import {hash,token,passwordHash} from '../auth.mjs';
import {accountAfterOrder} from '../customers.mjs';
let db,app;
const cfg={...config({NODE_ENV:'test',PUBLIC_URL:'http://localhost:3000',JWT_SECRET:'customer-tests-only-secret-1234567890'}),emailEnabled:true};
const write=(agent,method,path,body={})=>agent[method](path).set('Origin',cfg.publicUrl).set('X-Urfa-Request','1').send(body);
before(async()=>{db=await openDatabase({NODE_ENV:'test',LOCAL_DATABASE_PATH:'memory://'});await migrate(db);app=createApp(db,cfg);await db.query('INSERT INTO products(id,data) VALUES($1,$2)',['dish',JSON.stringify({name:'Dish',price:5,available:true,stockAvailable:true})]);await db.query('INSERT INTO admins(id,email,password_hash) VALUES($1,$2,$3)',[randomUUID(),'admin@example.com',await passwordHash('test-password-1234')]);});
after(()=>db.close());
async function customer(email){const id=randomUUID(),secret=token(),agent=request.agent(app);await db.query('INSERT INTO customers(id,email) VALUES($1,$2)',[id,email]);await db.query("INSERT INTO customer_tokens VALUES($1,$2,now()+interval '20 minutes')",[hash(secret),id]);const result=await write(agent,'post','/api/customer/verify',{token:secret});assert.equal(result.status,200);assert.match(result.headers['set-cookie'][0],/HttpOnly/);return {id,secret,agent};}
test('verified customer cannot access admin data and verification links cannot replay',async()=>{const c=await customer('one@example.com');assert.equal((await c.agent.get('/api/admin/carts')).status,401);assert.equal((await c.agent.get('/api/orders')).status,401);assert.equal((await write(c.agent,'post','/api/customer/verify',{token:c.secret})).status,401);await write(c.agent,'post','/api/customer/logout');assert.equal((await c.agent.get('/api/customer/me')).status,401);});
test('favorites and carts are private; cart edits do not prolong the 24h lifetime',async()=>{const a=await customer('a@example.com'),b=await customer('b@example.com');await write(a.agent,'put','/api/customer/favorites/dish');assert.deepEqual((await b.agent.get('/api/customer/favorites')).body,[]);const items=[{id:'dish',lineId:'dish',name:'Dish',quantity:1,price:5,imageUrl:''}];const saved=await write(a.agent,'put','/api/customer/cart',{items});assert.equal(saved.status,200);const changed=await write(a.agent,'put','/api/customer/cart',{items:[{...items[0],quantity:2}]});assert.equal(saved.body.expires_at,changed.body.expires_at);assert.deepEqual((await b.agent.get('/api/customer/cart')).body.items,[]);await db.query("UPDATE customer_carts SET expires_at=now()-interval '1 second' WHERE customer_id=$1",[a.id]);assert.deepEqual((await a.agent.get('/api/customer/cart')).body.items,[]);assert.equal((await db.query('SELECT * FROM customer_carts WHERE customer_id=$1',[a.id])).rows.length,0);});
test('first order creates one unverified account and queues one verification email',async()=>{await db.tx(tx=>accountAfterOrder(tx,cfg,'new@example.com'));await db.tx(tx=>accountAfterOrder(tx,cfg,'new@example.com'));const rows=(await db.query("SELECT * FROM customers WHERE email='new@example.com'")).rows;assert.equal(rows.length,1);assert.equal(rows[0].verified_at,null);assert.equal((await db.query("SELECT * FROM outbox WHERE recipient='new@example.com'")).rows.length,1);});
test('admin may see active carts; customers may not choose another customer identity',async()=>{const a=await customer('active@example.com');await write(a.agent,'put','/api/customer/cart',{items:[{id:'dish',lineId:'dish',name:'Dish',quantity:1,price:5,imageUrl:''}],customer_id:'someone-else'});const adm=request.agent(app);await write(adm,'post','/api/auth/login',{email:'admin@example.com',password:'test-password-1234'});const result=await adm.get('/api/admin/carts');assert.equal(result.status,200);assert.ok(result.body.some(c=>c.email==='active@example.com'));});
